apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: aws-standard-architecture
spec:
  modules:
  # VPC
    - name: aws-vpc
      variables:
      - name: enable_dns_hostnames
        value: true
#Internet Gateway
    - name: aws-internet-gateway
      alias: igw

# Subnet for Bastion and ROSA - Public
    - name: aws-vpc-subnets
      alias: pub_subnets
      dependencies:
        - name: gateways
          ref: igw
      variables:
      - name: label
        value: public
      - name: subnet_cidrs
        alias: pub_subnet_cidrs
        value:
          - 10.0.1.0/24
          - 10.0.2.0/24
          - 10.0.3.0/24
      - name: availability_zones
        value:
          - ap-south-1a
          - ap-south-1b
          - ap-south-1c

#NAT Gateway
    - name: aws-nat-gateway
      alias: ngw
      dependencies:
        - name: aws-vpc-subnets
          ref: pub_subnets      
      variables:
      - name : connectivity_type
        value: public   
      - name : _count
        value: 3   


# Subnet for ROSA - Private
    - name: aws-vpc-subnets
      alias: pri_subnets
      dependencies:
        - name: gateways
          ref: ngw
      variables:
      - name: label
        value: private
      - name: subnet_cidrs
        alias: pri_subnets_cidrs
        value:
          - 10.0.4.0/24
          - 10.0.5.0/24
          - 10.0.6.0/24
      - name: availability_zones
        value:
          - ap-south-1a
          - ap-south-1b
          - ap-south-1c
#ROSA 
    - name: aws-rosa
      dependencies:
        - name: public-subnets
          ref: pub_subnets
        - name: private-subnets
          ref: pri_subnets
      variables:
        - name: multi-zone-cluster
          value: true
        - name: no_of_compute_nodes
          value: 3
        - name: dry_run
          value: true
        - name: machine-cidr
          value:  10.0.0.0/16
        - name: service-cidr
          value: 172.30.0.0/16
        - name: pod-cidr
          value: 10.128.0.0/14
        - name: rosa_token          
          important: true
#Global value    
  variables:
    - name: name_prefix
      scope: global
      value: sw-bom
    - name: provision
      value: true
      scope: global    
    - name: resource_group_name
      value: std-arch
      scope: global        
    - name: region
      value: ap-south-1
      scope: global              